# Generated by Django 4.2.7 on 2025-03-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
